# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :booking do
    # after(:create) do |user, evaluator|; FactoryGirl.create_list :passenger, 2; end # commented to avoid circular reference
    # association :return_booking, factory: :booking
    # invoice # commented to avoid circular reference
    # payment_detail # commented to avoid circular reference
    # association :main, factory: :booking
    client
    stop
    trip
    user
    quantity 1
    sequence(:id)
  end

end
