# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do
  
  factory :bus do
    #after(:create) do |user, evaluator|; FactoryGirl.create_list :seat, 2; end # commented to avoid circular reference
    user
    capacity 1
    name 'Bus'
    year '1998'
    model 'Toyota'
    sequence(:id)
  end
  
end
