# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :charge do
    user
    percentage 10
    sequence(:id)
    description 'Test Charge'
  end

end
