# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do
  
  factory :charge do
    user
    sequence(:id)
    description 'Test Charge'
  end
  
end
