# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do
  
  factory :client do
    address
    name Faker::Name.first_name
    surname Faker::Name.last_name
    #after(:create) do |user, evaluator|; FactoryGirl.create_list :booking, 2; end # commented to avoid circular reference
    #after(:create) do |user, evaluator|; FactoryGirl.create_list :voucher, 2; end # commented to avoid circular reference
    bank
    user
    sequence(:id)
  end
  
end
