# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :connection do
    association :from, factory: :destination
    association :to, factory: :destination
    route
    sequence(:id)
  end

end
