# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do
  
  factory :destination do
    city
    route
    sequence(:id)
    sequence(:sequence)
  end
  
end
