# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do
  
  factory :discount do
    passenger_type
    user
    percentage 10
    sequence(:id)
  end
  
end
