# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :driver do
    name 'Jim'
    surname 'Johnson'
    user
    sequence(:id)
  end

end
