# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :invoice do
    # after(:create) do |user, evaluator|; FactoryGirl.create_list :line_item, 2; end # commented to avoid circular reference
    booking
    sequence(:id)
  end

end
