# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :line_item do
    invoice
    description 'Test Line Item'
    amount 100
    line_item_type :debit
    sequence(:id)
  end

end
