# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do
  
  factory :payment_detail do
    booking
    payment_type
    user
    sequence(:id)
  end
  
end
