# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :stop do
    # after(:create) do |user, evaluator|; FactoryGirl.create_list :booking, 2; end # commented to avoid circular reference
    arrive Time.now
    depart Time.now
    available_seats 10
    connection
    trip
    sequence(:id)
  end

end
