# original version autogenerated by Stepford: https://github.com/garysweaver/stepford

FactoryGirl.define do

  factory :trip do
    # after(:create) do |user, evaluator|; FactoryGirl.create_list :booking, 2; end # commented to avoid circular reference
    # after(:create) do |user, evaluator|; FactoryGirl.create_list :stop, 2; end # commented to avoid circular reference
    name 'EL-CT'
    bus
    route
    user
    sequence(:id)
  end

end
