AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - config/**/*
    
  TargetRubyVersion: 2.3   
    
Rails:
  Enabled: true

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing
  
Metrics/LineLength:
  Max: 120  
  
Metrics/MethodLength:
  Enabled: false 
  
Metrics/ClassLength:
  Enabled: false    

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false
  
Style/ClassAndModuleChildren:
  Enabled: false  
  